### ISSUE TITLE
Add new items

### ISSUE THREAD

**Issue by JuraRusan** [Strafbefehl/DeluxeHubReloaded#2]
Can you add new elements like the original developer did? 
https://github.com/ItsLewizzz/DeluxeHub/commit/ae6e7f654c2098a0268b4008fb70bd7522acf008#diff-41d7fdfebb364c46d51b384eb3d70fb836422344e5511fbdef2bfe2fc225219c

https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java

**Comment by JuraRusan** [comment]
Because when using material from 1.21, the plugin is disabled
```yaml
custom_join_items:
  # Should custom join items be enabled?
  enabled: true
  # Should we prevent them from moving/dropping the items?
  disable_inventory_movement: true

  items:
    menu:
      material: OMINOUS_TRIAL_KEY
      amount: 1
      slot: 4
      display_name: "&#caeaf5   Server menu   "
      actions:
        - "[COMMAND] menu"
```
