### ISSUE TITLE
'[PROXY] <server>' action does not transfer player to target server (Velocity)

### ISSUE THREAD

**Issue by lukasschr** [Strafbefehl/DeluxeHubReloaded#39]
I am experiencing an issue with the [PROXY] action not transferring the player to the target server when using Velocity as the proxy.

Here is a snippet from my serverselector.yml configuration:

```yaml
# Slots of the GUI
slots: 27

# Title of the GUI
title: "Server-Auswahl"

# Automatically update open inventories.
# This can be used to update placeholders in the GUI.
refresh:
  enabled: false
  rate: 40

# The items inside the GUI can be listed here
items:
  filler:
    material: GRAY_STAINED_GLASS_PANE
    slot: -1 # Setting the slot to -1 will fill every empty slot, you can also do "slots: [0, 1, 2]"
...
  vanilla:
    material: GRASS_BLOCK
    slot: 16
    amount: 1
    glow: false
    display_name: '&aVanilla (1.21.5)'
    lore:
      - '&7Stelle sicher, dass dein Client'
      - '&7die Version 1.21.5 hat'
    actions:
      - '[PROXY] vanilla'
      - '[CLOSE]'
```

The [PROXY] vanilla action does not seem to work correctly. When a player clicks the item, they are not transferred to the specified server via the proxy.

I am using Velocity as my proxy. However, when the player manually executes /server vanilla, they are transferred as expected.

I also tried replacing [PROXY] vanilla with [COMMAND] server vanilla, but that did not work either.

Is this a compatibility issue with Velocity, or am I missing something in the configuration?
