### ISSUE TITLE
Add unbreakable option to items

### ISSUE THREAD

**Issue by kikMine0** [Strafbefehl/DeluxeHubReloaded#54]
Make it so the config has an item with already the **Unbreakable** nbt flag so while in PvP Mode the items dont destroy
ex.
```YAML
material: BOW
      amount: 1
      unbreakable: true    # so the bow doesn't break
      enchantments:
      - INFINITY: 1
      - UNBREAKING: 3
```
