### ISSUE TITLE
always-day, always-night

### ISSUE THREAD

**Issue by postyizhan** [Strafbefehl/DeluxeHubReloaded#6]
Hello, I hope DeluxeHubReloaded to add 'always day' and 'always night' functions  
Thank you very much for maintaining DeluxeHubReloaded

**Comment by Strafbefehl** [comment]
Hello @postyizhan, I don't really know if this feature is necessary because you can also just set it with /gamerule

**Comment by postyizhan** [comment]
I think having this feature in the plugin would be more convenient......

**Comment by Strafbefehl** [comment]
In the config file or over a command ingame?

**Comment by postyizhan** [comment]
config file,
and add `disable player PVP`?

**Comment by deathbot159** [comment]
**StaticTime** module will be added in version **3.6.7**.
Disabling player pvp is supported via WorldSettings in config file:
```yaml
world_settings:
  # Player
  disable_hunger_loss: true
  disable_fall_damage: true
  disable_player_pvp: true <<<<
```
